#!/bin/sh

PREFIX=/usr
MAIN=

#findPrefix
if [ -x /bin/rpm ]
then
  MAIN=`rpm -ql metamorphose2|grep metamorphose2.py`
  if [ -f "$MAIN" ];then
    exec python3 $MAIN "$@"
    exit
  fi
fi
#findPrefixEnd

#run
if [ -d "$PREFIX/share/metamorphose2" ]
then
  exec python3 $PREFIX/share/metamorphose2/metamorphose2.py "$@"
else
  SRC_DIR=$(dirname ${0})
  exec python3 ${SRC_DIR}/src/metamorphose2.py "$@"
fi
